import type { Metadata } from "next";
import "./globals.css";
// layout.tsx
import { Inter, Noto_Sans_KR } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const noto = Noto_Sans_KR({
  variable: "--font-noto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative ${inter.variable} ${noto.variable} h-[clamp(540px,100vh,1200px)] w-screen overflow-x-hidden antialiased`}
      >
        {/* <Header /> */}
        {children}
      </body>
    </html>
  );
}
