import type { Metadata } from "next";
import "./globals.css";
// layout.tsx
import { Inter, Noto_Sans_KR } from "next/font/google";
import Header from "@/features/header";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const noto = Noto_Sans_KR({
  subsets: ["latin"],
  variable: "--font-noto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative ${inter.variable} ${noto.variable} h-[clamp(540px,100vh,1440px)] flex justify-center w-screen antialiased animate-none`}
      >
        <Header />
        <div className="flex flex-col w-full h-full overflow-y-auto overflow-x-hidden scrollbar-hide">{children}</div>
      </body>
    </html>
  );
}
